# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dPCA',
                'doc_host': 'https://waterboy96.github.io',
                'git_url': 'https://github.com/waterboy96/dPCA',
                'lib_path': 'dPCA'},
  'syms': {'dPCA.core': {'dPCA.core.foo': ('core.html#foo', 'dPCA/core.py')}}}
